import type { Locale } from "@/lib/i18n";

const APP = {
  fi: {
    navOverview: "Yhteenveto",
    navSearch: "Uusi haku",
    navHistory: "Aiemmat haut",
    navCompanies: "Yritykset",
    navPeople: "Päättäjät",
    navChanges: "Muutokset",
    navAccounts: "Asiakkaat",
    navTeam: "Tiimi",
    navIntegrations: "CRM",
    navProfiles: "Profiilit",
    navSchedules: "Ajastukset",
    navLists: "Listat",
    navReview: "Tarkistus",
    navDuplicates: "Kaksoiskappaleet",
    navSources: "Lähteet",
    navJobs: "Työt",
    navExports: "Viennit",
    navQuality: "Laatu",
    navAudit: "Lokit",
    navSecurity: "Turvallisuus",
    navPlan: "Tilaus",
    navSettings: "Asetukset",
    navTickets: "Tuki",
    navPrivacy: "Tietosuoja",
    navHome: "Koti",
    newSearch: "Uusi haku",
    idle: "Valmis",
    jobsRunning: "työtä käynnissä",
    checkingSession: "Istunto",
    openingWorkspace: "Avataan työtilaa…",
    sessionSlow: "Istunto kestää liian kauan. Kirjaudu uudelleen.",
    signIn: "Kirjaudu",
    admin: "Hallinta",
    workspace: "Työtila",
    unlimited: "Rajaton",
    loading: "Ladataan…",
    save: "Tallenna",
    saved: "Tallennettu",
    create: "Luo",
    cancel: "Peruuta",
    accept: "Hyväksy",
    reject: "Hylkää",
    remove: "Poista",
    yes: "Kyllä",
    no: "Ei",
    retry: "Yritä uudelleen",
    navGroupFind: "Haku",
    navGroupPipeline: "Myynti",
    navGroupOps: "Toiminnot",
    navGroupAccount: "Tili",
    findPlaceholder: "Hae yritystä, henkilöä, hakua…",
    workspaceTimeout: "Työtilan tilastot eivät ehtineet. Voit silti hakea.",
  },
  en: {
    navOverview: "Overview",
    navSearch: "Start search",
    navHistory: "Previous searches",
    navCompanies: "Companies",
    navPeople: "People",
    navChanges: "Changes",
    navAccounts: "Accounts",
    navTeam: "Team",
    navIntegrations: "CRM",
    navProfiles: "Profiles",
    navSchedules: "Schedules",
    navLists: "Lists",
    navReview: "Review",
    navDuplicates: "Duplicates",
    navSources: "Sources",
    navJobs: "Jobs",
    navExports: "Exports",
    navQuality: "Quality",
    navAudit: "Audit",
    navSecurity: "Security",
    navPlan: "Plan",
    navSettings: "Settings",
    navTickets: "Support",
    navPrivacy: "Privacy",
    navHome: "Home",
    newSearch: "New search",
    idle: "Idle",
    jobsRunning: "jobs running",
    checkingSession: "Checking session",
    openingWorkspace: "Opening workspace…",
    sessionSlow: "Session is taking too long. Sign in again.",
    signIn: "Sign in",
    admin: "Admin",
    workspace: "Workspace",
    unlimited: "Unlimited",
    loading: "Loading…",
    save: "Save",
    saved: "Saved",
    create: "Create",
    cancel: "Cancel",
    accept: "Accept",
    reject: "Reject",
    remove: "Remove",
    yes: "Yes",
    no: "No",
    retry: "Retry",
    navGroupFind: "Search",
    navGroupPipeline: "Pipeline",
    navGroupOps: "Operations",
    navGroupAccount: "Account",
    findPlaceholder: "Find a company, person, search…",
    workspaceTimeout: "Workspace stats timed out. You can still search.",
  },
  sv: {
    navOverview: "Översikt",
    navSearch: "Ny sökning",
    navHistory: "Tidigare sökningar",
    navCompanies: "Företag",
    navPeople: "Beslutsfattare",
    navChanges: "Ändringar",
    navAccounts: "Kunder",
    navTeam: "Team",
    navIntegrations: "CRM",
    navProfiles: "Profiler",
    navSchedules: "Scheman",
    navLists: "Listor",
    navReview: "Granskning",
    navDuplicates: "Dubbletter",
    navSources: "Källor",
    navJobs: "Jobb",
    navExports: "Export",
    navQuality: "Kvalitet",
    navAudit: "Logg",
    navSecurity: "Säkerhet",
    navPlan: "Plan",
    navSettings: "Inställningar",
    navTickets: "Support",
    navPrivacy: "Integritet",
    navHome: "Hem",
    newSearch: "Ny sökning",
    idle: "Klar",
    jobsRunning: "jobb igång",
    checkingSession: "Session",
    openingWorkspace: "Öppnar arbetsytan…",
    sessionSlow: "Sessionen tar för lång tid. Logga in igen.",
    signIn: "Logga in",
    admin: "Admin",
    workspace: "Arbetsyta",
    unlimited: "Obegränsad",
    loading: "Laddar…",
    save: "Spara",
    saved: "Sparat",
    create: "Skapa",
    cancel: "Avbryt",
    accept: "Godkänn",
    reject: "Avvisa",
    remove: "Ta bort",
    yes: "Ja",
    no: "Nej",
    retry: "Försök igen",
    navGroupFind: "Sök",
    navGroupPipeline: "Pipeline",
    navGroupOps: "Drift",
    navGroupAccount: "Konto",
    findPlaceholder: "Sök företag, person, sökning…",
    workspaceTimeout: "Arbetsytans statistik tog för lång tid. Du kan ändå söka.",
  },
} as const;

export type AppMsg = keyof (typeof APP)["fi"];

export function ta(locale: Locale, key: AppMsg): string {
  return APP[locale][key] ?? APP.en[key] ?? key;
}

export const NAV_GROUPS: Array<{ key: AppMsg; items: Array<{ to: string; key: AppMsg }> }> = [
  {
    key: "navGroupFind",
    items: [
      { to: "/overview", key: "navOverview" },
      { to: "/search/new", key: "navSearch" },
      { to: "/search", key: "navHistory" },
      { to: "/companies", key: "navCompanies" },
      { to: "/people", key: "navPeople" },
    ],
  },
  {
    key: "navGroupPipeline",
    items: [
      { to: "/lists", key: "navLists" },
      { to: "/profiles", key: "navProfiles" },
      { to: "/schedules", key: "navSchedules" },
      { to: "/review", key: "navReview" },
      { to: "/accounts", key: "navAccounts" },
      { to: "/changes", key: "navChanges" },
    ],
  },
  {
    key: "navGroupOps",
    items: [
      { to: "/team", key: "navTeam" },
      { to: "/sources", key: "navSources" },
      { to: "/integrations", key: "navIntegrations" },
      { to: "/jobs", key: "navJobs" },
      { to: "/exports", key: "navExports" },
    ],
  },
  {
    key: "navGroupAccount",
    items: [
      { to: "/quality", key: "navQuality" },
      { to: "/audit", key: "navAudit" },
      { to: "/security", key: "navSecurity" },
      { to: "/billing", key: "navPlan" },
      { to: "/tickets", key: "navTickets" },
      { to: "/settings", key: "navSettings" },
      { to: "/privacy", key: "navPrivacy" },
    ],
  },
];

export const NAV_ITEMS: Array<{ to: string; key: AppMsg }> = NAV_GROUPS.flatMap((g) => g.items);

export const TAB_ITEMS: Array<{ to: string; key: AppMsg }> = [
  { to: "/overview", key: "navHome" },
  { to: "/search/new", key: "navSearch" },
  { to: "/companies", key: "navCompanies" },
  { to: "/people", key: "navPeople" },
];
