/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppChangesRouteImport } from './routes/_app/changes'
import { Route as AppDuplicatesRouteImport } from './routes/_app/duplicates'
import { Route as AppExportsRouteImport } from './routes/_app/exports'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppListsRouteImport } from './routes/_app/lists'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppPrivacyRouteImport } from './routes/_app/privacy'
import { Route as AppProfilesRouteImport } from './routes/_app/profiles'
import { Route as AppQualityRouteImport } from './routes/_app/quality'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppSchedulesRouteImport } from './routes/_app/schedules'
import { Route as AppSecurityRouteImport } from './routes/_app/security'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSourcesRouteImport } from './routes/_app/sources'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminDataNetworkRouteImport } from './routes/admin/data-network'
import { Route as AdminMailRouteImport } from './routes/admin/mail'
import { Route as AdminSearchRouteImport } from './routes/admin/search'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminSeoRouteImport } from './routes/admin/seo'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as ApiDebugRouteImport } from './routes/api/debug'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as IndustriesIndexRouteImport } from './routes/industries/index'
import { Route as IndustriesSlugRouteImport } from './routes/industries/$slug'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LocationsSlugRouteImport } from './routes/locations/$slug'
import { Route as MarketsSlugRouteImport } from './routes/markets/$slug'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsBusinessIdRouteImport } from './routes/tools/business-id'
import { Route as ToolsCompanyFinderRouteImport } from './routes/tools/company-finder'
import { Route as ToolsWebsiteQualityRouteImport } from './routes/tools/website-quality'
import { Route as UseCasesIndexRouteImport } from './routes/use-cases/index'
import { Route as UseCasesSlugRouteImport } from './routes/use-cases/$slug'
import { Route as AppCompaniesIndexRouteImport } from './routes/_app/companies/index'
import { Route as AppCompaniesCompanyIdRouteImport } from './routes/_app/companies/$companyId'
import { Route as AppPeopleIndexRouteImport } from './routes/_app/people/index'
import { Route as AppPeoplePersonIdRouteImport } from './routes/_app/people/$personId'
import { Route as AppSearchIndexRouteImport } from './routes/_app/search/index'
import { Route as AppSearchRunIdRouteImport } from './routes/_app/search/$runId'
import { Route as AppSearchNewRouteImport } from './routes/_app/search/new'
import { Route as AppTicketsIndexRouteImport } from './routes/_app/tickets/index'
import { Route as AppTicketsTicketIdRouteImport } from './routes/_app/tickets/$ticketId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronTickRouteImport } from './routes/api/cron/tick'
import { Route as ApiGscCallbackRouteImport } from './routes/api/gsc/callback'
import { Route as ApiInternalCanaryRouteImport } from './routes/api/internal/canary'
import { Route as ApiInternalWorkerRouteImport } from './routes/api/internal/worker'
import { Route as ApiJobsDrainRouteImport } from './routes/api/jobs/drain'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as SupportTTokenRouteImport } from './routes/support/t/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppChangesRoute = AppChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => AppRoute,
} as any)
const AppDuplicatesRoute = AppDuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => AppRoute,
} as any)
const AppExportsRoute = AppExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppListsRoute = AppListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesRoute = AppProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppSchedulesRoute = AppSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataNetworkRoute = AdminDataNetworkRouteImport.update({
  id: '/data-network',
  path: '/data-network',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMailRoute = AdminMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const ApiDebugRoute = ApiDebugRouteImport.update({
  id: '/api/debug',
  path: '/api/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsSlugRoute = MarketsSlugRouteImport.update({
  id: '/markets/$slug',
  path: '/markets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBusinessIdRoute = ToolsBusinessIdRouteImport.update({
  id: '/tools/business-id',
  path: '/tools/business-id',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCompanyFinderRoute = ToolsCompanyFinderRouteImport.update({
  id: '/tools/company-finder',
  path: '/tools/company-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWebsiteQualityRoute = ToolsWebsiteQualityRouteImport.update({
  id: '/tools/website-quality',
  path: '/tools/website-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesIndexRoute = UseCasesIndexRouteImport.update({
  id: '/use-cases/',
  path: '/use-cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesSlugRoute = UseCasesSlugRouteImport.update({
  id: '/use-cases/$slug',
  path: '/use-cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompaniesIndexRoute = AppCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesCompanyIdRoute = AppCompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AppRoute,
} as any)
const AppPeoplePersonIdRoute = AppPeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchIndexRoute = AppSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRunIdRoute = AppSearchRunIdRouteImport.update({
  id: '/search/$runId',
  path: '/search/$runId',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchNewRoute = AppSearchNewRouteImport.update({
  id: '/search/new',
  path: '/search/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsIndexRoute = AppTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsTicketIdRoute = AppTicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronTickRoute = ApiCronTickRouteImport.update({
  id: '/api/cron/tick',
  path: '/api/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGscCallbackRoute = ApiGscCallbackRouteImport.update({
  id: '/api/gsc/callback',
  path: '/api/gsc/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalCanaryRoute = ApiInternalCanaryRouteImport.update({
  id: '/api/internal/canary',
  path: '/api/internal/canary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalWorkerRoute = ApiInternalWorkerRouteImport.update({
  id: '/api/internal/worker',
  path: '/api/internal/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsDrainRoute = ApiJobsDrainRouteImport.update({
  id: '/api/jobs/drain',
  path: '/api/jobs/drain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportTTokenRoute = SupportTTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => SupportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRouteWithChildren
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/accounts': typeof AppAccountsRoute
  '/audit': typeof AppAuditRoute
  '/billing': typeof AppBillingRoute
  '/changes': typeof AppChangesRoute
  '/duplicates': typeof AppDuplicatesRoute
  '/exports': typeof AppExportsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/jobs': typeof AppJobsRoute
  '/lists': typeof AppListsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/overview': typeof AppOverviewRoute
  '/privacy': typeof AppPrivacyRoute
  '/profiles': typeof AppProfilesRoute
  '/quality': typeof AppQualityRoute
  '/review': typeof AppReviewRoute
  '/schedules': typeof AppSchedulesRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/team': typeof AppTeamRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/data-network': typeof AdminDataNetworkRoute
  '/admin/mail': typeof AdminMailRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/api/debug': typeof ApiDebugRoute
  '/api/health': typeof ApiHealthRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/markets/$slug': typeof MarketsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/tools/business-id': typeof ToolsBusinessIdRoute
  '/tools/company-finder': typeof ToolsCompanyFinderRoute
  '/tools/website-quality': typeof ToolsWebsiteQualityRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/use-cases/': typeof UseCasesIndexRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/people/$personId': typeof AppPeoplePersonIdRoute
  '/search/$runId': typeof AppSearchRunIdRoute
  '/search/new': typeof AppSearchNewRoute
  '/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/gsc/callback': typeof ApiGscCallbackRoute
  '/api/internal/canary': typeof ApiInternalCanaryRoute
  '/api/internal/worker': typeof ApiInternalWorkerRoute
  '/api/jobs/drain': typeof ApiJobsDrainRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/support/t/$token': typeof SupportTTokenRoute
  '/companies/': typeof AppCompaniesIndexRoute
  '/people/': typeof AppPeopleIndexRoute
  '/search/': typeof AppSearchIndexRoute
  '/tickets/': typeof AppTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRouteWithChildren
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/accounts': typeof AppAccountsRoute
  '/audit': typeof AppAuditRoute
  '/billing': typeof AppBillingRoute
  '/changes': typeof AppChangesRoute
  '/duplicates': typeof AppDuplicatesRoute
  '/exports': typeof AppExportsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/jobs': typeof AppJobsRoute
  '/lists': typeof AppListsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/overview': typeof AppOverviewRoute
  '/privacy': typeof AppPrivacyRoute
  '/profiles': typeof AppProfilesRoute
  '/quality': typeof AppQualityRoute
  '/review': typeof AppReviewRoute
  '/schedules': typeof AppSchedulesRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/team': typeof AppTeamRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/data-network': typeof AdminDataNetworkRoute
  '/admin/mail': typeof AdminMailRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/api/debug': typeof ApiDebugRoute
  '/api/health': typeof ApiHealthRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/markets/$slug': typeof MarketsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/tools/business-id': typeof ToolsBusinessIdRoute
  '/tools/company-finder': typeof ToolsCompanyFinderRoute
  '/tools/website-quality': typeof ToolsWebsiteQualityRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/news': typeof NewsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/use-cases': typeof UseCasesIndexRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/people/$personId': typeof AppPeoplePersonIdRoute
  '/search/$runId': typeof AppSearchRunIdRoute
  '/search/new': typeof AppSearchNewRoute
  '/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/gsc/callback': typeof ApiGscCallbackRoute
  '/api/internal/canary': typeof ApiInternalCanaryRoute
  '/api/internal/worker': typeof ApiInternalWorkerRoute
  '/api/jobs/drain': typeof ApiJobsDrainRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/support/t/$token': typeof SupportTTokenRoute
  '/companies': typeof AppCompaniesIndexRoute
  '/people': typeof AppPeopleIndexRoute
  '/search': typeof AppSearchIndexRoute
  '/tickets': typeof AppTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRouteWithChildren
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/changes': typeof AppChangesRoute
  '/_app/duplicates': typeof AppDuplicatesRoute
  '/_app/exports': typeof AppExportsRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/lists': typeof AppListsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/profiles': typeof AppProfilesRoute
  '/_app/quality': typeof AppQualityRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/schedules': typeof AppSchedulesRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sources': typeof AppSourcesRoute
  '/_app/team': typeof AppTeamRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/data-network': typeof AdminDataNetworkRoute
  '/admin/mail': typeof AdminMailRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/api/debug': typeof ApiDebugRoute
  '/api/health': typeof ApiHealthRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/markets/$slug': typeof MarketsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/tools/business-id': typeof ToolsBusinessIdRoute
  '/tools/company-finder': typeof ToolsCompanyFinderRoute
  '/tools/website-quality': typeof ToolsWebsiteQualityRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/use-cases/': typeof UseCasesIndexRoute
  '/_app/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/_app/people/$personId': typeof AppPeoplePersonIdRoute
  '/_app/search/$runId': typeof AppSearchRunIdRoute
  '/_app/search/new': typeof AppSearchNewRoute
  '/_app/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/gsc/callback': typeof ApiGscCallbackRoute
  '/api/internal/canary': typeof ApiInternalCanaryRoute
  '/api/internal/worker': typeof ApiInternalWorkerRoute
  '/api/jobs/drain': typeof ApiJobsDrainRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/support/t/$token': typeof SupportTTokenRoute
  '/_app/companies/': typeof AppCompaniesIndexRoute
  '/_app/people/': typeof AppPeopleIndexRoute
  '/_app/search/': typeof AppSearchIndexRoute
  '/_app/tickets/': typeof AppTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/faq'
    | '/legal'
    | '/login'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/unsubscribe'
    | '/accounts'
    | '/audit'
    | '/billing'
    | '/changes'
    | '/duplicates'
    | '/exports'
    | '/integrations'
    | '/jobs'
    | '/lists'
    | '/onboarding'
    | '/overview'
    | '/privacy'
    | '/profiles'
    | '/quality'
    | '/review'
    | '/schedules'
    | '/security'
    | '/settings'
    | '/sources'
    | '/team'
    | '/admin/activity'
    | '/admin/blog'
    | '/admin/data-network'
    | '/admin/mail'
    | '/admin/search'
    | '/admin/security'
    | '/admin/seo'
    | '/admin/support'
    | '/admin/team'
    | '/api/debug'
    | '/api/health'
    | '/guides/$slug'
    | '/industries/$slug'
    | '/locations/$slug'
    | '/markets/$slug'
    | '/news/$slug'
    | '/tools/business-id'
    | '/tools/company-finder'
    | '/tools/website-quality'
    | '/use-cases/$slug'
    | '/admin/'
    | '/guides/'
    | '/industries/'
    | '/locations/'
    | '/news/'
    | '/tools/'
    | '/use-cases/'
    | '/companies/$companyId'
    | '/people/$personId'
    | '/search/$runId'
    | '/search/new'
    | '/tickets/$ticketId'
    | '/api/auth/$'
    | '/api/cron/tick'
    | '/api/gsc/callback'
    | '/api/internal/canary'
    | '/api/internal/worker'
    | '/api/jobs/drain'
    | '/api/stripe/webhook'
    | '/support/t/$token'
    | '/companies/'
    | '/people/'
    | '/search/'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/legal'
    | '/login'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/unsubscribe'
    | '/accounts'
    | '/audit'
    | '/billing'
    | '/changes'
    | '/duplicates'
    | '/exports'
    | '/integrations'
    | '/jobs'
    | '/lists'
    | '/onboarding'
    | '/overview'
    | '/privacy'
    | '/profiles'
    | '/quality'
    | '/review'
    | '/schedules'
    | '/security'
    | '/settings'
    | '/sources'
    | '/team'
    | '/admin/activity'
    | '/admin/blog'
    | '/admin/data-network'
    | '/admin/mail'
    | '/admin/search'
    | '/admin/security'
    | '/admin/seo'
    | '/admin/support'
    | '/admin/team'
    | '/api/debug'
    | '/api/health'
    | '/guides/$slug'
    | '/industries/$slug'
    | '/locations/$slug'
    | '/markets/$slug'
    | '/news/$slug'
    | '/tools/business-id'
    | '/tools/company-finder'
    | '/tools/website-quality'
    | '/use-cases/$slug'
    | '/admin'
    | '/guides'
    | '/industries'
    | '/locations'
    | '/news'
    | '/tools'
    | '/use-cases'
    | '/companies/$companyId'
    | '/people/$personId'
    | '/search/$runId'
    | '/search/new'
    | '/tickets/$ticketId'
    | '/api/auth/$'
    | '/api/cron/tick'
    | '/api/gsc/callback'
    | '/api/internal/canary'
    | '/api/internal/worker'
    | '/api/jobs/drain'
    | '/api/stripe/webhook'
    | '/support/t/$token'
    | '/companies'
    | '/people'
    | '/search'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/admin'
    | '/faq'
    | '/legal'
    | '/login'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/unsubscribe'
    | '/_app/accounts'
    | '/_app/audit'
    | '/_app/billing'
    | '/_app/changes'
    | '/_app/duplicates'
    | '/_app/exports'
    | '/_app/integrations'
    | '/_app/jobs'
    | '/_app/lists'
    | '/_app/onboarding'
    | '/_app/overview'
    | '/_app/privacy'
    | '/_app/profiles'
    | '/_app/quality'
    | '/_app/review'
    | '/_app/schedules'
    | '/_app/security'
    | '/_app/settings'
    | '/_app/sources'
    | '/_app/team'
    | '/admin/activity'
    | '/admin/blog'
    | '/admin/data-network'
    | '/admin/mail'
    | '/admin/search'
    | '/admin/security'
    | '/admin/seo'
    | '/admin/support'
    | '/admin/team'
    | '/api/debug'
    | '/api/health'
    | '/guides/$slug'
    | '/industries/$slug'
    | '/locations/$slug'
    | '/markets/$slug'
    | '/news/$slug'
    | '/tools/business-id'
    | '/tools/company-finder'
    | '/tools/website-quality'
    | '/use-cases/$slug'
    | '/admin/'
    | '/guides/'
    | '/industries/'
    | '/locations/'
    | '/news/'
    | '/tools/'
    | '/use-cases/'
    | '/_app/companies/$companyId'
    | '/_app/people/$personId'
    | '/_app/search/$runId'
    | '/_app/search/new'
    | '/_app/tickets/$ticketId'
    | '/api/auth/$'
    | '/api/cron/tick'
    | '/api/gsc/callback'
    | '/api/internal/canary'
    | '/api/internal/worker'
    | '/api/jobs/drain'
    | '/api/stripe/webhook'
    | '/support/t/$token'
    | '/_app/companies/'
    | '/_app/people/'
    | '/_app/search/'
    | '/_app/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  FaqRoute: typeof FaqRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRouteWithChildren
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiDebugRoute: typeof ApiDebugRoute
  ApiHealthRoute: typeof ApiHealthRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  MarketsSlugRoute: typeof MarketsSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  ToolsBusinessIdRoute: typeof ToolsBusinessIdRoute
  ToolsCompanyFinderRoute: typeof ToolsCompanyFinderRoute
  ToolsWebsiteQualityRoute: typeof ToolsWebsiteQualityRoute
  UseCasesSlugRoute: typeof UseCasesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  UseCasesIndexRoute: typeof UseCasesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronTickRoute: typeof ApiCronTickRoute
  ApiGscCallbackRoute: typeof ApiGscCallbackRoute
  ApiInternalCanaryRoute: typeof ApiInternalCanaryRoute
  ApiInternalWorkerRoute: typeof ApiInternalWorkerRoute
  ApiJobsDrainRoute: typeof ApiJobsDrainRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/changes': {
      id: '/_app/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof AppChangesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/duplicates': {
      id: '/_app/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof AppDuplicatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exports': {
      id: '/_app/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AppExportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists': {
      id: '/_app/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof AppListsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles': {
      id: '/_app/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AppProfilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality': {
      id: '/_app/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedules': {
      id: '/_app/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AppSchedulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data-network': {
      id: '/admin/data-network'
      path: '/data-network'
      fullPath: '/admin/data-network'
      preLoaderRoute: typeof AdminDataNetworkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mail': {
      id: '/admin/mail'
      path: '/mail'
      fullPath: '/admin/mail'
      preLoaderRoute: typeof AdminMailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/debug': {
      id: '/api/debug'
      path: '/api/debug'
      fullPath: '/api/debug'
      preLoaderRoute: typeof ApiDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$slug': {
      id: '/markets/$slug'
      path: '/markets/$slug'
      fullPath: '/markets/$slug'
      preLoaderRoute: typeof MarketsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/business-id': {
      id: '/tools/business-id'
      path: '/tools/business-id'
      fullPath: '/tools/business-id'
      preLoaderRoute: typeof ToolsBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/company-finder': {
      id: '/tools/company-finder'
      path: '/tools/company-finder'
      fullPath: '/tools/company-finder'
      preLoaderRoute: typeof ToolsCompanyFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/website-quality': {
      id: '/tools/website-quality'
      path: '/tools/website-quality'
      fullPath: '/tools/website-quality'
      preLoaderRoute: typeof ToolsWebsiteQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/': {
      id: '/use-cases/'
      path: '/use-cases'
      fullPath: '/use-cases/'
      preLoaderRoute: typeof UseCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/$slug': {
      id: '/use-cases/$slug'
      path: '/use-cases/$slug'
      fullPath: '/use-cases/$slug'
      preLoaderRoute: typeof UseCasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/companies/': {
      id: '/_app/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AppCompaniesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies/$companyId': {
      id: '/_app/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AppCompaniesCompanyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/': {
      id: '/_app/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/$personId': {
      id: '/_app/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AppPeoplePersonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search/': {
      id: '/_app/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof AppSearchIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search/$runId': {
      id: '/_app/search/$runId'
      path: '/search/$runId'
      fullPath: '/search/$runId'
      preLoaderRoute: typeof AppSearchRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search/new': {
      id: '/_app/search/new'
      path: '/search/new'
      fullPath: '/search/new'
      preLoaderRoute: typeof AppSearchNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets/': {
      id: '/_app/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AppTicketsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets/$ticketId': {
      id: '/_app/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AppTicketsTicketIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/tick': {
      id: '/api/cron/tick'
      path: '/api/cron/tick'
      fullPath: '/api/cron/tick'
      preLoaderRoute: typeof ApiCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gsc/callback': {
      id: '/api/gsc/callback'
      path: '/api/gsc/callback'
      fullPath: '/api/gsc/callback'
      preLoaderRoute: typeof ApiGscCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/canary': {
      id: '/api/internal/canary'
      path: '/api/internal/canary'
      fullPath: '/api/internal/canary'
      preLoaderRoute: typeof ApiInternalCanaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/worker': {
      id: '/api/internal/worker'
      path: '/api/internal/worker'
      fullPath: '/api/internal/worker'
      preLoaderRoute: typeof ApiInternalWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/drain': {
      id: '/api/jobs/drain'
      path: '/api/jobs/drain'
      fullPath: '/api/jobs/drain'
      preLoaderRoute: typeof ApiJobsDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/t/$token': {
      id: '/support/t/$token'
      path: '/t/$token'
      fullPath: '/support/t/$token'
      preLoaderRoute: typeof SupportTTokenRouteImport
      parentRoute: typeof SupportRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBillingRoute: typeof AppBillingRoute
  AppChangesRoute: typeof AppChangesRoute
  AppDuplicatesRoute: typeof AppDuplicatesRoute
  AppExportsRoute: typeof AppExportsRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppJobsRoute: typeof AppJobsRoute
  AppListsRoute: typeof AppListsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppProfilesRoute: typeof AppProfilesRoute
  AppQualityRoute: typeof AppQualityRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSchedulesRoute: typeof AppSchedulesRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSourcesRoute: typeof AppSourcesRoute
  AppTeamRoute: typeof AppTeamRoute
  AppCompaniesCompanyIdRoute: typeof AppCompaniesCompanyIdRoute
  AppPeoplePersonIdRoute: typeof AppPeoplePersonIdRoute
  AppSearchRunIdRoute: typeof AppSearchRunIdRoute
  AppSearchNewRoute: typeof AppSearchNewRoute
  AppTicketsTicketIdRoute: typeof AppTicketsTicketIdRoute
  AppCompaniesIndexRoute: typeof AppCompaniesIndexRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
  AppSearchIndexRoute: typeof AppSearchIndexRoute
  AppTicketsIndexRoute: typeof AppTicketsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAuditRoute: AppAuditRoute,
  AppBillingRoute: AppBillingRoute,
  AppChangesRoute: AppChangesRoute,
  AppDuplicatesRoute: AppDuplicatesRoute,
  AppExportsRoute: AppExportsRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppJobsRoute: AppJobsRoute,
  AppListsRoute: AppListsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppProfilesRoute: AppProfilesRoute,
  AppQualityRoute: AppQualityRoute,
  AppReviewRoute: AppReviewRoute,
  AppSchedulesRoute: AppSchedulesRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSourcesRoute: AppSourcesRoute,
  AppTeamRoute: AppTeamRoute,
  AppCompaniesCompanyIdRoute: AppCompaniesCompanyIdRoute,
  AppPeoplePersonIdRoute: AppPeoplePersonIdRoute,
  AppSearchRunIdRoute: AppSearchRunIdRoute,
  AppSearchNewRoute: AppSearchNewRoute,
  AppTicketsTicketIdRoute: AppTicketsTicketIdRoute,
  AppCompaniesIndexRoute: AppCompaniesIndexRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
  AppSearchIndexRoute: AppSearchIndexRoute,
  AppTicketsIndexRoute: AppTicketsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminDataNetworkRoute: typeof AdminDataNetworkRoute
  AdminMailRoute: typeof AdminMailRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminDataNetworkRoute: AdminDataNetworkRoute,
  AdminMailRoute: AdminMailRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SupportRouteChildren {
  SupportTTokenRoute: typeof SupportTTokenRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportTTokenRoute: SupportTTokenRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  FaqRoute: FaqRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRouteWithChildren,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiDebugRoute: ApiDebugRoute,
  ApiHealthRoute: ApiHealthRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  MarketsSlugRoute: MarketsSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  ToolsBusinessIdRoute: ToolsBusinessIdRoute,
  ToolsCompanyFinderRoute: ToolsCompanyFinderRoute,
  ToolsWebsiteQualityRoute: ToolsWebsiteQualityRoute,
  UseCasesSlugRoute: UseCasesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  UseCasesIndexRoute: UseCasesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronTickRoute: ApiCronTickRoute,
  ApiGscCallbackRoute: ApiGscCallbackRoute,
  ApiInternalCanaryRoute: ApiInternalCanaryRoute,
  ApiInternalWorkerRoute: ApiInternalWorkerRoute,
  ApiJobsDrainRoute: ApiJobsDrainRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
